import streamlit as st

def competitors_page():
    st.markdown("<h1 style='font-size: 50px; color:#FF5733;'>Competitors</h1>", unsafe_allow_html=True)
    st.write("""
        Here are some of the key competitors of SwarNeTT, each offering unique solutions in mass notifications and emergency communications.
    """)
    
    competitors = {
        "Everbridge Mass Notification": "Everbridge Mass Notification is a communication platform that can send notifications across over twenty-five contact paths, including desktop alerts, including push notifications. Organizations can reach individuals and groups using lists, locations, and visual intelligence. Everbridge integrates with Geographic Information Systems (GIS) capabilities, which allows for updates based on geographic regions. Additionally, it offers global communication with multi-lingual support, text-to-speech technology, and a “globally local” approach for managing contacts across distributed data stores. The application is available on the Google Play Store, Apple App Store, and, for desktop download.",
        "AlertMedia": "AlertMedia is a cloud-based communication platform designed for businesses to send and receive notifications across multiple channels such as email, SMS, voice calls, social media, and app push notifications. It can be used for regular business communication or critical emergency alerts. This platform works by integrating with existing business communication systems with an intuitive mass notification system (MNS) similar to Everbridge. The application is available on the Google Play Store, Apple App Store, and, for desktop via web browsers.",
        "FEMA": "FEMA, developed by the Federal Emergency Management Agency in the United States, aims to assist people before, during, and after disasters. The application aids users in preparation for emergencies by using basic preparedness strategies such as family emergency communication plans, emergency kits planning, and educating users on actions to take in the event of a hazard. It offers real-time weather and emergency alerts from the National Weather Service for up to five locations nationwide. The application uses public data feeds available through the Integrated Public Alert and Warning System (IPAWS) to get its alerts. FEMA also provides tools for recovery after disasters such as locating Disaster Recovery Centers and assists in finding nearby shelters during evacuation. Available on the Google Play Store, Apple App Store, and for desktop via web browsers.",
        "Zello Walkie Talkie": "Zello Walkie Talkie is an application that transforms a smartphone into a push-to-talk (PTT) walkie-talkie, delivering secure private channels and broadcasts over cellular networks and Wi-Fi. Zello promises seamless functionality even on the lowest-grade cellular data networks, ensuring communication across any network or device, anywhere in the world. It adjusts to make use of whatever bandwidth is available in cases of unstable networks. The application is valuable to professionals in emergency response industries, providing a quick and easy access to emergency alerts with a simple push. Zello also offers a free option for emergency response personnel, with unlimited users, channels, and gateways at no cost for five years. Available as a desktop and Android app.",
        "PansTT": "The Public Alert Notification System (PANS) launched as part of National Disaster Preparedness Month (NDPPM) in 2023, provides a mass notification system for the Office of Disaster Preparedness and Management (ODPM) in Trinidad and Tobago. PANS sends emergency alerts nationally to affected areas or groups. It supports persons with disabilities by allowing them to choose their preferred medium of communication. The system supports multi-platform communication across various channels for registered users, including phone calls, SMS text messages, email, and even fax.",
        "goTenna": "goTenna is a radio device that pairs with mobile applications to create a peer-to-peer network that operates independently of cellular, Wi-Fi, and satellite systems. It features fully off-grid mesh networking capabilities, ensuring users remain well-informed throughout every mission. goTenna Pro and Pro X radios pair with any iOS or Android smartphone for collaborative mapping, messaging, and personnel tracking in areas without cellular, Wi-Fi, or satellite connectivity. It is used by over 350 agencies worldwide for mission-critical operations, especially in remote areas. Available for both Android and iOS, goTenna is a vital tool for off-grid communications."
    }

    # Display competitors with dropdowns (expanders)
    for competitor, description in competitors.items():
        with st.expander(f"**{competitor}**"): 
            st.write(f"<div style='font-size: 18px; color: #333;'>{description}</div>", unsafe_allow_html=True)

